#! /usr/bin/env python3
"""Regenerate ``OpenGL/raw/<API>/_glgets.py`` from ``src/glgetsizes.csv``.

The full code generator (:mod:`xml_generate`) needs ``lxml`` plus a checked-out
Khronos registry to rebuild everything.  This lightweight regenerator only needs
the CSV -- the human-maintained source of truth for glGet output sizes -- plus
the enum *name -> value* mapping, which it recovers from the existing
``_glgets.py`` files (enum values never change, only the sizes we correct do).

Use it after editing ``glgetsizes.csv`` to correct a size or remove a ``#TODO``
marker::

    python src/regen_glgets.py            # rewrite every raw/<API>/_glgets.py
    python src/regen_glgets.py --check     # fail if any file is out of date

It reproduces the exact format the full generator emits: entries sorted by enum
name, ``_m[<value>] = <size> # <NAME>``, with any trailing ``#TODO`` text from
the CSV concatenated straight after the size (so removing the CSV's third column
removes the TODO from the generated module).
"""

import os
import re
import sys
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # repo root holding ``OpenGL``
CSV = os.path.join(HERE, 'glgetsizes.csv')

HEADER = (
    '"""glGet* auto-generation of output arrays (DO NOT EDIT, AUTOGENERATED)"""\n'
    'try:\n'
    '    from OpenGL.raw.GL._lookupint import LookupInt as _L\n'
    'except ImportError:\n'
    '    def _L(*args):\n'
    '        raise RuntimeError( "Need to define a lookupint for this api" )\n'
    '_glget_size_mapping = _m = {}\n'
)

#: matches a generated line, capturing value, size-expression and trailing NAME.
_LINE = re.compile(r'^_m\[([^\]]+)\]\s*=\s*(.*?)\s*#\s*([A-Za-z0-9_]+)\s*$')


def load_csv(path=CSV):
    """Return ordered ``[(name, size_str), ...]`` from the CSV.

    Mirrors ``codegenerator.loadGLGetSizes`` + ``group_sizes``: columns after the
    name are stripped of quotes, empties dropped, and the remainder joined -- so
    a ``(1,)`` size with a ``#TODO ...`` third column becomes ``(1,)#TODO ...``.
    """
    out = []
    with open(path) as fh:
        for raw in fh.read().splitlines():
            if not raw:
                continue
            cols = raw.split('\t')
            name = cols[0].strip('"').strip()
            if not name:
                continue
            size = ''.join([c for c in (c.strip('"') for c in cols[1:]) if c])
            if size:
                out.append((name, size))
    return out


def _registry_values():
    """``{enum_name: '0x...'}`` from the Khronos registry, if available.

    Lets the CSV add brand-new pnames (whose value isn't in any ``_glgets.py``
    yet) and still have them emitted.  Best-effort: returns ``{}`` when gl.xml is
    absent so the regenerator still works offline from the existing modules.
    """
    import xml.etree.ElementTree as ET
    for cand in (os.environ.get('GL_XML'),
                 os.path.join(HERE, 'khronosapi', 'xml', 'gl.xml')):
        if cand and os.path.exists(cand):
            root = ET.parse(cand).getroot()
            out = {}
            for en in root.iter('enum'):
                name, value = en.get('name'), en.get('value')
                if name and value and name not in out:
                    out[name] = value
            return out
    return {}


_REGISTRY = None


def name_to_value(api='GL'):
    """``{enum_name: value_token}`` from an existing ``_glgets.py`` plus, as a
    fallback for new pnames, the Khronos registry."""
    global _REGISTRY
    if _REGISTRY is None:
        _REGISTRY = _registry_values()
    module = {}
    path = os.path.join(ROOT, 'OpenGL', 'raw', api, '_glgets.py')
    with open(path) as fh:
        for line in fh:
            m = _LINE.match(line.strip())
            if m:
                value, _size, name = m.groups()
                module[name] = value
    # EGL/GLX/WGL keep an empty glget table; only augment APIs that already carry
    # the GL/GLES size table (so the registry fallback can add new GL pnames there
    # without bloating the windowing-system modules).
    if not module:
        return module
    mapping = dict(_REGISTRY)
    mapping.update(module)                      # existing module wins (proven value)
    return mapping


def render(csv_rows, n2v):
    """Render the full ``_glgets.py`` body for the given name->value mapping."""
    lines = []
    missing = []
    for name, size in sorted(csv_rows, key=lambda r: r[0]):
        value = n2v.get(name)
        if value is None:
            missing.append(name)
            continue
        lines.append('_m[%s] = %s # %s' % (value, size, name))
    return HEADER + '\n'.join(lines) + '\n', missing


def api_dirs():
    return sorted(
        os.path.dirname(p)
        for p in glob.glob(os.path.join(ROOT, 'OpenGL', 'raw', '*', '_glgets.py'))
    )


def main(argv):
    check = '--check' in argv
    csv_rows = load_csv()
    stale = []
    for d in api_dirs():
        api = os.path.basename(d)
        body, missing = render(csv_rows, name_to_value(api))
        target = os.path.join(d, '_glgets.py')
        current = open(target).read()
        if current == body:
            continue
        if check:
            stale.append(api)
        else:
            open(target, 'w').write(body)
            extra = ' (%d csv names had no known value)' % len(missing) if missing else ''
            print('updated %s%s' % (os.path.relpath(target, ROOT), extra))
    if check and stale:
        print('OUT OF DATE: %s' % ', '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
